### ISSUE TITLE
More suitable colors for rulers 

### ISSUE THREAD

**Issue by krutoo** [benjaminbenais/codesandbox-dark-theme#1]
Hi, i use this theme in VS Code but rulers looks some agressive:

![image](https://user-images.githubusercontent.com/13140130/97256239-5813f100-1834-11eb-945e-7c522ff0a8c1.png)

I think it can look better like in black theme: https://github.com/siddharthkp/codesandbox-black-vscode-theme/issues/1

Is it possible to change?

**Comment by benjaminbenais** [comment]
Hi @krutoo , thanks for the feedback.

I've updated the rulers colors to match the color of the main foreground. Hope this helps.
Let me know if it's still too agressive. Otherwise, feel free to make a pull request.

**Comment by krutoo** [comment]
@benjaminbenais how can i see updates? It is still almost white in codesandbox:

![image](https://user-images.githubusercontent.com/13140130/97973802-748dcb80-1de8-11eb-8343-9f86131dbc21.png)

**Comment by benjaminbenais** [comment]
@krutoo Did you get the new version of the extension in VSCode ? To make sure you can uninstall and reinstall it.

If it's still too white you can submit a merge request with your change. The name of the field to modify the color of the rulers is `editorRuler.foreground`

**Comment by CoderZ90** [comment]
> @krutoo Did you get the new version of the extension in VSCode ? To make sure you can uninstall and reinstall it.
> 
> If it's still too white you can submit a merge request with your change. The name of the field to modify the color of the rulers is `editorRuler.foreground`

Your extension is incredible but what **font** you used in the screenshot please reply because i really like the font you used

**Comment by benjaminbenais** [comment]
> > @krutoo Did you get the new version of the extension in VSCode ? To make sure you can uninstall and reinstall it.
> > If it's still too white you can submit a merge request with your change. The name of the field to modify the color of the rulers is `editorRuler.foreground`
> 
> Your extension is incredible but what **font** you used in the screenshot please reply because i really like the font you used

The font used in the screenshots is [Dank Mono](https://gumroad.com/l/dank-mono).
