### ISSUE TITLE
QUESTION

### ISSUE THREAD

**Issue by dolphin007x** [benjaminbenais/codesandbox-dark-theme#3]
@benjaminbenais  What font was used in the screenshots by the way?

**Comment by benjaminbenais** [comment]
@Adatta1276 The font is [Cascadia Code](https://github.com/microsoft/cascadia-code).

**Comment by dolphin007x** [comment]
Thanks @benjaminbenais !!

**Comment by dolphin007x** [comment]
Any specific variant ? @benjaminbenais
